### ISSUE TITLE
[Feature Request] add unmount button to ESP mount partition window

### ISSUE THREAD

**Issue by SomeName6** [ic005k/QtOpenCoreConfig#125]
It should be nice if there will be added an unmount button to the ESP mount partition window. 

Now when the partition is already mounted and I click on Mount and open Config.plist the config doesn't open. Adding a detection mechanism which can detect if the partition is mounted should be nice.

**Comment by ic005k** [comment]
Why do you need to manipulate this mounted ESP partition via OCAT when you have already mounted it?
Because at this point, this ESP partition is like an ordinary hard disk partition, and you can operate it directly through File Manager, so if you go back to operate this disk through OCAT, wouldn't it be too inefficient?
So, after the ESP partition is mounted, it is operated directly through the file manager and there is absolutely no need to operate it through OCAT.

**Comment by ic005k** [comment]
Also, after the ESP partition is mounted, the drive letter will exist inside the file manager and it will act like a normal folder, so there is absolutely no need to go back and manipulate it via OCAT.

**Comment by SomeName6** [comment]
I just like the way of being able to unmount a partition from OCAT. Opencore configurator and ESP mounter pro does have this feature and that's pretty useful for me

Un mounting it in finder works fine...
