### ISSUE TITLE
To many updates

### ISSUE THREAD

**Issue by Erik262** [ic005k/QtOpenCoreConfig#130]
Hi,

I like this program and it works perfectly! But since I have put this repo on the watchlist for new releases I'm getting a lot of annoying notifications about new releases every day. Wouldnt it be easier to use a version number like v 1.0.2 or something, instead of the date and pushing once a week or something?

**Comment by ic005k** [comment]
First of all, thank you for your attention.
For an app that is updated very frequently, it might not be a good idea for you to put it on the watchlist.
Why does OCAT update so often? The reasons are as follows.
1. The APP has a lot of areas that need to be improved.
2. I don't have enough whole block of time to perfect it.
3. I can only use some fragmented time to complete the APP.
So, when I have a little time, I will update the APP, but I dare not accumulate it, otherwise I may forget some things like user's suggestion.
Simply put, OCAT is not following the model of commercial APP at all, its release and update are full of randomness, without any plan at all (and no need for any plan).
Regarding the version number, the year is added to distinguish it from OC's version number, for example, 20220106, which means the 106th update in 2022.
Finally, as always, I will keep improving this app, and when you find that it is no longer updated one day, it means it is more perfect, hopefully tomorrow.
Also, I'd like to say that it's the first time I've encountered users complaining about an app updating too often, which surprised me a bit. But this is the last time I will reply to a similar question, I will ignore such questions later, it's a bit of a waste of time to reply to such questions.

**Comment by Erik262** [comment]
I'm not complaining about the updates; I'm happy to see improvements and bug fixes. But it is not common to release something so frequently like this repo. I have never seen this in any program or repo before, pushing an update 4 to 6 times a day. People like me check Github notifications every day and don't want to get flooded. 

But it's okay, I will remove/unsubscribe it from the watchlist like suggested, to not "waste my time" clicking every time on Done. 👌
