### ISSUE TITLE
Kext Update

### ISSUE THREAD

**Issue by dipakvz** [ic005k/QtOpenCoreConfig#79]
After selecting multiple kexts, if we press "Check Kexts updates online" button, first kext of list will be green highlighted and this button + update button grayed, after that no further progress to check kexts updates for all other kexts.

above mentioned both button can be usable after we press stop button.

I am not sure, it is a bug or I am making mistake to understand kext update function. I just bring it to your kind attention.
![Screenshot 2021-11-27 at 6 39 48 AM](https://user-images.githubusercontent.com/64690604/143663818-3ee04009-2604-430a-8c13-c99ec4a7f2c4.png)

**Comment by ic005k** [comment]
Please wait patiently for it to finish checking. When it's done, the "Check for updates" button will automatically light up, and the "Upgrade" button will automatically light up if an update is available, all automatically. " The purpose of the "Stop" button is to stop it manually if the network does not answer for a long time so that the process of checking for updates never finishes. Wait for the network failure to be removed and then "check for updates" again.
This is nothing, a very simple process, but of course, if you encounter obstacles to updating, please try again after selecting the appropriate network proxy in the "Database" screen.

**Comment by ic005k** [comment]
Also, the green color on the entry is the progress bar for checking updates, which is in motion, not stationary, and it goes from 0 to 100%.

**Comment by ic005k** [comment]
Here's how to set up a download proxy, please use Google Web Translator to understand the following.

https://github.com/ic005k/QtOpenCoreConfig/issues/73

**Comment by dipakvz** [comment]
Thanks for the update & detailed instructions of this function.

Your software is swiss army knife for hackintosher....once again, thanks
for the same.

**Comment by dipakvz** [comment]
It was due to proxy selection, Now working fine.
