### ISSUE TITLE
Ability to stick to latest official (non-beta) OC release, while using up-to-date OCAT

### ISSUE THREAD

**Issue by viking1304** [ic005k/QtOpenCoreConfig#80]
First of all, thank you very much for this fantastic tool. I have no issues, only one small suggestion.

I think it might be good to add ability to update OC to latest non-beta OC release, while using up-to-date OCAT. Maybe this might look like a ridiculous request at first, but let me explain why I am suggesting this.

OC 0.7.6 is currently, at least officially, in beta stage. Even 0.7.6 is probably rock solid, users might not get proper support from OC team if they are using beta release. That's why I think it would be good to be able to stick to 0.7.5 until 0.7.6 is [officially released](https://github.com/acidanthera/opencorepkg/releases).

I honestly have no idea what would be best approach to accomplish this, but please at least think about this. And yes, I am fully aware that anyone can find previous release of your tool that will do exactly what I am suggesting.

**Comment by ic005k** [comment]
First of all, thank you for your advice.
Frankly, on this point, I have not found a perfect solution yet.
Because OCAT has a database, which is both the highlight and the baggage of OCAT, so keeping both the official version and the development version of OC inside an app will face multiple databases (the official version's database and the development version's database), which will only end up making OCAT more and more bloated and difficult to maintain, and possibly buggy.
So, when no better solution is found, the current method is the best.
In the meantime, if you have any better ideas, please feel free to let me know, thanks.

**Comment by ic005k** [comment]
If OCAT didn't have a database of OC's built in, then everything would be easy. I just need to make a programmatic judgement between different OC versions and I'm done.
But again, OCAT's database is not to be discarded, as it provides a very convenient way to upgrade OC.
So, it's a dilemma. But keeping it simple has been the design goal of OCAT since its inception, and that will never change; OCAT will only get simpler and easier to use.

**Comment by ic005k** [comment]
Currently, this is solved by adding the "OpenCore DEV" option to the "Edit" menu.
This way, the problem you mentioned will be gone.
More ideas are welcome, thanks.

**Comment by ic005k** [comment]
Currently, this is solved by adding the "OpenCore DEV" option to the "Edit" menu.
This way, the problem you mentioned will be gone.
More ideas are welcome, thanks.
