### ISSUE TITLE
New Series of Changes for MacOS

### ISSUE THREAD

**Issue by LucasMucGH** [ic005k/QtOpenCoreConfig#89]
Hello ic005k,

I have fully tested the app today and I have come up with a new list of ideas on how I think the app could be made even more intuitive on macOS. This time a lot more work went in and most of the changes are visualized with a screenshot and markup.  I invite again @llity and @5T33Z0 to join the discourse. Like last time this is just my opinion and every suggestion is subjective. However, this time I will explain in detail why I propose the changes, to avoid misunderstandings.

Due to the size of the proposed changes and the fact that the other issue already has 40 comments I thought it is appropriate to create a new issue.

![1](https://user-images.githubusercontent.com/63545066/145677114-0c94bb56-0f39-4156-9631-e9bacc11ae80.png)

1. ~I would open an about window when you press on `About OCAuxilliaryTools`, like on Xcode (**yellow**). I would remove the _app name_ from the toolbar, because it would be visible in the status bar as well as in the new about window (**red**). I would also remove the _version_ of the app from the toolbar and move it to the about window (**green**). I would leave out the _Acknowledgments_ and _License Agreement_ button (from Xcode) as we don't need them (**blue**). I would replace the _copyright_ with the _MIT license_ or omit it completely (**blue**).~

![2](https://user-images.githubusercontent.com/63545066/145677128-c1a0ec0e-7d5a-4f55-ae97-69aea698dbbd.png)

2. ~I would open a preferences window when you press on `Preferences`, like in Xcode (**yellow**). I would move the `Misc` and "`Kext Upgrade URL`" in there (**blue**). I would also move the _4 dots_ under `Misc` in the form of a picker (**green**).~

![3](https://user-images.githubusercontent.com/63545066/145677137-379365cc-94ad-4d4e-9074-93c4aa521396.png)

3. I would implement the search function (`Find`) like _Xcode_ for example. That is put a `Find` area in the status bar (**yellow**) and when selected open a `Find` field. Since the _search bar_ is now no longer needed in the toolbar, I would give the option to hide it (see other 3.).

![4](https://user-images.githubusercontent.com/63545066/145677144-4f28740e-3f8d-42cb-aa16-abafe1e17c66.png)

4. ~Since every button of the `toolbar` is now available in the statusbar i would provide an option under macOS to hide the `toolbar` completely and then show it like in the screenshot instead (**blue**).~

Other:
1. ~I still don't really understand what the `Browse Catalog` button does. Does it just open finder? If so I would either remove it completely or change the toolbar icon as it doesn't really represent the action. If not, it would be nice if you could explain what it is for. Then maybe I can bring a suggestion how to make it more self-explanatory.~

2. ~I would add keyboard shortcuts, especially for `Undo` and `Redo`.~

3. I would add in the "Misc" settings, for completeness, the option to hide also the "Save", "OC Validate", "Synchronize OC main program", "Undo" and "Redo".

Im not sure it is possible to archive this behavior, because of the cross platform nature of the app. If not, don't mind to close it immediately.  

Greetings,
Lucas

**Comment by 5T33Z0** [comment]
@ic005k Thanks for updating the mount feature!!! makes it lot more useful if you have more than one drive installed.

**Comment by 5T33Z0** [comment]
Updated Quirks list.

- Added Booter, Kernel and UEFI Quirks for Intel Alder Lake
- Renamed "Intel 1st Gen" etc.  to "Intel Core 1st Gen"
- Restructured the list: Desktop first, then High End Dektop since it's more common 

**Files**: https://github.com/5T33Z0/OC-Little-Translated/tree/main/F_Desktop_EFIs/preset

**Comment by 5T33Z0** [comment]
Suggestion: Add Kext sfor Intel Wifi and Bluetooth:

- Intel Wifi: https://github.com/OpenIntelWireless/itlwm/releases
- Intel Bluetooth: https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases

**Comment by junaedahmed** [comment]
It would be great if all the kexts from [OC Docs](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Kexts.md) are added to the preset kext update list.

**Comment by 5T33Z0** [comment]
@junaedahmed 

I think most of them are already included:

├── ALC256.kext
├── AMDRyzenCPUPowerManagement.kext
├── ATH9KFixup.kext
├── AirportBrcmFixup.kext
├── AppleALC.kext
├── AppleALCU.kext
├── AppleMCEReporterDisabler.kext
├── AtherosE2200Ethernet.kext
├── BlueToolFixup.kext
├── BrcmBluetoothInjector.kext
├── BrcmBluetoothInjectorLegacy.kext
├── BrcmFirmwareData.kext
├── BrcmFirmwareRepo.kext
├── BrcmNonPatchRAM.kext
├── BrcmNonPatchRAM2.kext
├── BrcmPatchRAM.kext
├── BrcmPatchRAM2.kext
├── BrcmPatchRAM3.kext
├── BrightnessKeys.kext
├── CPUFriend.kext
├── CPUFriendDataProvider.kext
├── CpuTscSync.kext
├── DebugEnhancer.kext
├── ECEnabler.kext
├── FakeSMC.kext
├── FeatureUnlock.kext
├── HibernationFixup.kext
├── HoRNDIS9.2.kext
├── Innie.kext
├── IntelMausi.kext
├── IntelSnowMausi.kext
├── Lilu.kext
├── LucyRTL8125Ethernet.kext
├── MacProMemoryNotificationDisabler.kext
├── NVMeFix.kext
├── NightShiftEnabler.kext
├── NoTouchID.kext
├── RTCMemoryFixup.kext
├── RealtekCardReader.kext
├── RealtekCardReaderFriend.kext
├── RealtekRTL8111-2.2.2.kext
├── RealtekRTL8111.kext
├── RestrictEvents.kext
├── SMCAMDProcessor.kext
├── SMCBatteryManager.kext
├── SMCDellSensors.kext
├── SMCLightSensor.kext
├── SMCProcessor.kext
├── SMCSuperIO.kext
├── USBInjectAll.kext
├── VirtualSMC.kext
├── VoodooI2C.kext
├── VoodooI2CAtmelMXT.kext
├── VoodooI2CELAN.kext
├── VoodooI2CFTE.kext
├── VoodooI2CHID.kext
├── VoodooI2CSynaptics.kext
├── VoodooInput.kext
├── VoodooPS2Controller.kext
├── WhateverGreen.kext
└── XLNCUSBFix.kext

**Comment by ic005k** [comment]
"Browse Catalog"
Browses the relevant directory where the currently opened Config.plist is located.
For example, if OCAT is in the "Kext" user interface, open the "EFI/OC/Kexts" directory.
This is a very useful and convenient feature for you to manage EFI files quickly.

**Comment by ic005k** [comment]
@LucasMucGH 

Please download the latest version, OCAT can now hide the toolbar.

**Comment by ic005k** [comment]
> Suggestion: Add Kexts for Intel Wifi and Bluetooth

These files are too big, and it seems that its distribution rules are different from other kext, the downloaded kext are all with the same file name, which is not convenient to handle automatically, because there will be the same name overwriting phenomenon.
So, about this issue, it is better for users to add and manage the Kext upgrade URL by themselves, OCAT currently does not do default additions.

**Comment by LucasMucGH** [comment]
@ic005k 

Thank you, I checked out the latest release and updated the original post.

First of all, thank you for adding the `About OCAuxilliaryTools` window - it is great! Just one suggestion: if possible, it would be great if you could make the app logo in the about section a litte bit lager. Also the "For" should be lowercase: "Version ... for OpenCore ...".

The `Preferences` window is also really great, as well as the option to hide the toolbar! It makes the app look much more clean.

**Comment by 5T33Z0** [comment]
I like that "Preferences" and "About" section have their own entries now. The About section should contain Credits to those who contributed. I also like the customizing options.

What I don't like: 
- I think replacing the icon-based buttons (which contained `+`, `-`, &uarr;, &darr;) by text buttons is a mistake and a step backward. Everybody recognizes &uarr; and &darr; arrows and + and - symbols. Not so much for english text-only buttons.

**Comment by LucasMucGH** [comment]
> I think replacing the icon-based buttons (which contained +, -, ↑, ↓) by text buttons is a mistake and a step backward. Everybody recognizes ↑ and ↓ arrows and + and - symbols. Not so much for english text-only buttons.

I personally think there should be an option in the settings to switch between text and image based buttons. I personally prefer the image based ones, too, but I’m a big fan of customization.

**Comment by ic005k** [comment]
@5T33Z0  @LucasMucGH 

Removing the button icons was a choice of last resort, as they always had a very disjointed look and lacked a unified design.
As of now, there are no volunteers willing to design the whole set of icons for OCAT, most of the current icons are what I found from the internet, and you will find that OCAT's icons are very messy, which is the result of the lack of unified design.
A good app must have a professional UI icon designer to work with in order to look more dynamic, and obviously OCAT lacks this.
Therefore, it is a good choice to use icons carefully in the later maintenance.
Especially for macOS dark mode, it must have two sets of icons to be very perfect (one set for normal mode and one set for dark mode). But anyway, I can't find any ready-made icons for normal mode and dark mode on the Internet, which is very difficult for me, and also very time-consuming, because it must be designed to get, and there is no ready-made one that can be used immediately.
If you are willing to design icons for OCAT, I would be happy to continue to improve OCAT's UI and look forward to your performance.
Thanks.

**Comment by LucasMucGH** [comment]
Unfortunately I’m not a graphics designer. But for my own apps I mostly use SFSymbols and Icons8 (https://icons8.com/). SFSymbols is only available on apple devices, but icons8 is free. The free version of Icons8 has only lower resolution formats and you need to link to Icons8 in the about section, but the lower resolution images are still really great and the linking doesn’t hurts anyone. So I would suggest to use Icons8. Hundred thousands of great images for free.

**Comment by 5T33Z0** [comment]
Compared to how the GUI looked in the beginning it has come pretty far already.

**Comment by 5T33Z0** [comment]
You should just call the buttons "Add" and "Delete". No need for "Item". If anything, these are 2 Words anyway.

**Comment by ic005k** [comment]
And I also have a decision to remove these buttons and move these to the right-click menu, so that the whole user interface will be cleaner.
Later on, I might also remove the toolbar completely (and not offer hidden options) to really keep it minimal.
Frankly speaking, I like @LucasMucGH's suggestion a lot, from a developer's point of view, I think we share the same idea, I should have met you earlier, thanks.
Actually, at the beginning, OCAT's design went astray, there was no need to design the toolbar at all, it was a real redundancy, and the toolbar was criticized by many users for being a Windows style thing.
When OCAT was first launched, users kept saying, "Hey, this is a Windows app," and from that time on I should have realized that the design was going in the wrong direction and should have been corrected, but luckily I met @LucasMucGH and it's not too late to correct it.

Also, if time allows, I even thought of rewriting OCAT directly in XCode + Swift, since Swift also has cross-platform capabilities already.

**Comment by 5T33Z0** [comment]
From an ease of use perspective, I think hiding essential functions like move, add, delete and preset into a right-click sub-menue is the wrong decision unless you can click and drag list entries. 

In other words:
- Make entries moveable by mouse (If you can't move entries by mouse don't hide the move buttons).
- keep +/- Buttons or add/delete
- hide the rest in a righ-click menu.

 I also believe removing the toolbar is the wrong decision since you already implemented a hide function for it.

**Comment by ic005k** [comment]
@5T33Z0

OCAT is still far from perfect, but rest assured that ease of use and user experience are always a priority at OCAT. Your input is always welcome, thank you.

**Comment by 5T33Z0** [comment]
Shortcuts don't work in macO.

Please bring the buttons back. You are making this app worse!

**Comment by Baio1977** [comment]
Hi, I'm Alessio and thank you for this fabulous App.
Help in a telegram group to do Hackintosh, I open many config every day, the evolution of the app has led to the elimination of the bar to move the order of kext or ACPI and this in my opinion is a serious loss, change by 10 position 1 Kext is not possible now, and it cannot even be dragged with the mouse .....
Can you go back to earlier with this option ???
Thank you so much

**Comment by LucasMucGH** [comment]
> Shortcuts don't work in macOS.
> Please bring the buttons back. You are making this app worse!

They work for me (also MacOS) perfectly fine and I think that was no mistake to remove those buttons. Im fine with the current implementation, but I have what do you think of this idea @5T33Z0:

![Screenshot 2021-12-13 at 21 21 51](https://user-images.githubusercontent.com/63545066/145883342-523b3ac6-aa20-43f9-874c-e8bf1900dada.png)

There would be a "+" and a "-" button for adding and removing entries and you could drag the entries for moving them.

I personally like the current implementation, but if it looks like it is a big problem for you and this could be a good solution.

**Comment by 5T33Z0** [comment]
Digger, du bist 16 Jahre alt. Woher willst du wissen, was gute Lösungen sind?

Die Kernfunktion einer App in ein rechts-click menü zu verbannen, nur damit die GUI besser aussieht ist eine beschissene Idee. Ich bin raus. Kein Bock mehr mich damit zu beschäftigen.

**Comment by LucasMucGH** [comment]
@5T33Z0 

Nichts für ungut, aber ich weiß nicht was das mit meinem Alter zu tun haben soll. Ich bin im Gegensatz zu älteren Generation mit der Technik aufgewachsen.

Außerdem finde ich es echt unhöflich, dass du hier direkt persönlich wirst. Schon als du gefordert hattest, dass der “Open Recent” button bleibt, wurde mir allmählich bewusst das du die App nicht für den end-Nutzer, sondern nur für dich optimieren möchtest. So aggressiv und subjektiv die Entwicklung einer App zu beeinflussen, nur für den eigenen Nutzen, ist echt beschämend.

Und selbst wenn du der Meinung warst, dass deine Vorschläge die App für alle optimieren würden, hatte ich bei jedem Issue betont, dass es nur meine Meinung ist und man es durchaus anders sehen kann. Design ist ein sehr kontroverses Thema und jeder Künstler, Designer, Entwickler und Firma hat ihre eigene Philosophie. Wenn du so viel reifer bist als ich 16jähriger, solltest du auch bitte in der Lage sein andere Meinungen zu aktzeptieren und respektieren.

~Lucas

**Comment by 5T33Z0** [comment]
Ich sag mal so: wenn Du hier Änderungsvorschläge einer App auf Grund **deines** **persönlichen** **Geschmaks** machst, die meine Arbeit mit dem Tool erschweren, betrifft mich das persönlich sehr. Und jetzt weißt du wie sich das anfühlt! Es geht hier nicht um Meiningen. es geht darum dass Dein Handeln meine User Experience mit der App negativ beeinflusst! Und das muss ich nicht respektieren.

Alter = Erfahrung. Das ist der einzige relevante Bezugspunkt. Ich bin knapp 30 Jahre älter als Du und habe dementsprechend mehr Erfahrung was die Bedienbarkeit von Apps angeht und habe diese ganzen Dinge kommen und gehen sehen: Apps mit zu überladener GUI, Apps mit zu wenig Schaltflächen, Apps mit unnötig komplizierter Bedienung.

Und dein Input hat auf Grund deiner falschen Fokussierung auf die Oberflächen objektiv dazu geführt, dass die App nun schlechter und ineffizienter in der Bedienung  geworden ist  als vorher – und das finde ich beschämend! Bist du UI  Designer? Nein! Also was erzählst Du hier von End-User – der bin ich nämlich auch. Wer hat dich zum Fürsprecher DER USER erkoren?

Und jetzt erstell mal bitte 10 configs from scratch und dann kannste ja mal überlegen, ob da wirklich so schlau war, das alles in Kontextmenüs zu vestecken. Denn hättest du das mal gemacht, dann wüsstest du ganz genau, warum es sinnlos ist das zu tun.

**Comment by ic005k** [comment]
@LucasMucGH 

I would like to improve this app of QtiASL, please give your valuable comments, thanks.

https://github.com/ic005k/QtiASL

**Comment by ic005k** [comment]
@LucasMucGH 

QtiASL is a DSDT editor and I would like to make it a little better, please be bold and give your opinion, I like your point of view as well as your intuition and look forward to your suggestions.
